# Generated by Django 5.1.6 on 2025-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_department_feedback_question_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
