# Generated by Django 5.1.6 on 2025-03-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0003_feedback_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquery",
            name="department",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
