# Generated by Django 5.1.6 on 2025-03-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0004_remove_userquery_department_delete_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquery",
            name="response_sent",
        ),
    ]
